### ISSUE TITLE
Install Instructions ? Errors?

### ISSUE THREAD

**Issue by mfcabrera** [rejeep/jq.el#3]
Hi I am trying to install it and I have installed Cask. I am using Mac OSX.
I set  `Emacs=/Applications/Emacs.app/Contents/MacOS/Emacs`

I ran make and it works:

    cask exec ert-runner
    .

    Ran 1 test in 0.000 seconds
    cask exec ecukes
    .......

    8 scenarios (0 failed, 8 passed)
    29 steps (0 failed, 0 skipped, 29 passed)

However when I run `make install`. Nothing happens... I check my `.emacs.d` directory but no `jq.el` there. I ended up copying it manually and it worked. but I guess there's should be a way to do it. 

Cheers!

**Comment by rejeep** [comment]
Hey, we are in the progress of merging this with https://github.com/ljos/jq-mode, please use that instead. I will update the readme.
